use super::*;
use tsz_binder::BinderState;
use tsz_common::position::LineMap;
use tsz_parser::ParserState;
use tsz_solver::TypeInterner;
include!("completions_tests_parts/part_00.rs");
include!("completions_tests_parts/part_01.rs");
include!("completions_tests_parts/part_02.rs");
include!("completions_tests_parts/part_03.rs");
include!("completions_tests_parts/part_04.rs");
include!("completions_tests_parts/part_05.rs");
include!("completions_tests_parts/part_06.rs");
include!("completions_tests_parts/part_07.rs");
include!("completions_tests_parts/part_08.rs");
include!("completions_tests_parts/part_09.rs");
include!("completions_tests_parts/part_10.rs");
include!("completions_tests_parts/part_11.rs");
include!("completions_tests_parts/part_12.rs");
include!("completions_tests_parts/part_13.rs");
include!("completions_tests_parts/part_14.rs");
include!("completions_tests_parts/part_15.rs");
