use crate::resolver::ScopeWalker;
use tsz_binder::{BinderState, symbol_flags};
use tsz_parser::ParserState;
use tsz_parser::parser::node::NodeAccess;
use tsz_scanner::SyntaxKind;
include!("resolver_tests_parts/part_00.rs");
include!("resolver_tests_parts/part_01.rs");
include!("resolver_tests_parts/part_02.rs");
include!("resolver_tests_parts/part_03.rs");
include!("resolver_tests_parts/part_04.rs");
include!("resolver_tests_parts/part_05.rs");
include!("resolver_tests_parts/part_06.rs");
include!("resolver_tests_parts/part_07.rs");
include!("resolver_tests_parts/part_08.rs");
include!("resolver_tests_parts/part_09.rs");
include!("resolver_tests_parts/part_10.rs");
