use super::*;
use crate::jsdoc::jsdoc_for_node;
use crate::utils::find_node_at_offset;
use tsz_binder::BinderState;
use tsz_common::position::LineMap;
use tsz_parser::ParserState;
use tsz_parser::syntax_kind_ext;
use tsz_solver::TypeInterner;
include!("signature_help_tests_parts/part_00.rs");
include!("signature_help_tests_parts/part_01.rs");
include!("signature_help_tests_parts/part_02.rs");
include!("signature_help_tests_parts/part_03.rs");
include!("signature_help_tests_parts/part_04.rs");
include!("signature_help_tests_parts/part_05.rs");
include!("signature_help_tests_parts/part_06.rs");
include!("signature_help_tests_parts/part_07.rs");
include!("signature_help_tests_parts/part_08.rs");
include!("signature_help_tests_parts/part_09.rs");
include!("signature_help_tests_parts/part_10.rs");
