use super::*;

use crate::context::transform::TransformDirective;

use crate::transforms::async_es5_ir::AsyncES5Transformer;

use rustc_hash::FxHashSet;

use tsz_common::common::ModuleKind;

use tsz_parser::parser::node::FunctionData;

use tsz_parser::parser::node_flags;

use tsz_parser::syntax::transform_utils::{
    collect_class_computed_name_this_references, contains_new_target_reference,
    contains_super_reference,
};

#[path = "class_es5_ast_to_ir_classes.rs"]
mod classes;

#[path = "class_es5_ast_to_ir_comments.rs"]
mod comments;

#[path = "class_es5_ast_to_ir_control_flow.rs"]
mod control_flow;

#[path = "class_es5_ast_to_ir_expressions.rs"]
mod expressions;

#[path = "class_es5_ast_to_ir_for_in_of.rs"]
mod for_in_of;

#[derive(Clone)]
enum ThisSubstitution {
    Identifier(String),
    Raw(String),
}

/// Convert an AST node to IR, avoiding `ASTRef` when possible
pub struct AstToIr<'a> {
    arena: &'a NodeArena,
    source_text: Option<&'a str>,
    /// Track if we're inside an arrow function that captures `this`
    this_captured: Cell<bool>,
    /// Transform directives from `LoweringPass`
    transforms: Option<TransformContext>,
    /// Base indentation for class declarations converted directly by this statement converter.
    class_transformer_indent_base: u32,
    /// Whether ES5 for-of lowering should use the full iterator protocol.
    downlevel_iteration: bool,
    /// Current `this` substitution to use when lowering static initializer contexts.
    current_this_substitution: Cell<Option<ThisSubstitution>>,
    /// Capture alias for lexical `this` inside arrows within the current member body.
    lexical_this_capture_alias: Cell<Option<ThisSubstitution>>,
    /// Whether we're inside a derived class (has extends clause) — needed for super lowering
    has_super: bool,
    /// Generated super parameter name for the class IIFE.
    super_name: String,
    /// Whether super access should use `_super.X` instead of `_super.prototype.X`.
    /// This is also enabled while converting nested non-arrow functions, where
    /// invalid `super` references follow tsc's recovery emit path.
    is_static: Cell<bool>,
    /// Optional identifier substitution for class self-references in decorated class bodies.
    identifier_substitution: Option<(String, String)>,
    /// Counter for generating unique temp variable names (shared with caller)
    temp_var_counter: Cell<u32>,
    /// Temp variable names that need `var` declarations at an enclosing scope
    hoisted_temps: RefCell<Vec<String>>,
    /// Counter for AMD/UMD dynamic import promise callback names.
    dynamic_import_promise_counter: Cell<u32>,
    /// Original module kind when this converter runs inside a module wrapper.
    module_kind: ModuleKind,
    target_es5: bool,
    /// Static block recovery mode where bare `await` identifiers are emitted
    /// as recovered `yield` tokens, matching `tsc` downlevel emit.
    emit_await_as_yield: bool,
    /// Do not attach trailing comments that begin at or after this source
    /// position. Used when converting statements inside a method/accessor body
    /// so comments after the body closing brace stay on the descriptor.
    trailing_comment_limit: Cell<Option<u32>>,
    /// Counter for `env_N`/`e_N` names used by lowered `using` regions.
    disposable_env_counter: Cell<u32>,
    /// Names already unavailable for disposable env/error temps.
    blocked_disposable_env_names: RefCell<FxHashSet<String>>,
    /// Disposable names generated by this converter for the caller to reserve.
    generated_disposable_env_names: RefCell<Vec<String>>,
    /// Outer block-scope rename map: original name → emitted name for
    /// let/const variables in enclosing scopes that were renamed during ES5
    /// lowering (e.g. `let x` → `var x_1` when shadowing an outer `x`).
    /// References inside class bodies must use the renamed form.
    outer_rename_map: rustc_hash::FxHashMap<String, String>,
    /// Maps clean private field name → `WeakMap` variable name for `__classPrivateFieldGet/Set`.
    /// Populated from the enclosing class's `PrivateFieldInfo` collection.
    private_field_map: rustc_hash::FxHashMap<String, String>,
    /// Maps clean private accessor name → getter `WeakMap` variable name.
    private_get_accessor_map: rustc_hash::FxHashMap<String, String>,
    /// Maps clean private accessor name → setter `WeakMap` variable name.
    private_set_accessor_map: rustc_hash::FxHashMap<String, String>,
}

include!("class_es5_ast_to_ir_parts/part1.rs");
include!("class_es5_ast_to_ir_parts/part2.rs");
