use super::*;
use crate::construction::TypeInterner;
use crate::def::DefId;
use crate::instantiation::instantiate::{TypeSubstitution, instantiate_type};
use crate::relations::subtype::SubtypeChecker;

// Split into under-cap shards to satisfy AGENTS section 19 while preserving test order.
include!("evaluate_tests_parts/part_00.rs");
include!("evaluate_tests_parts/part_01.rs");
include!("evaluate_tests_parts/part_02.rs");
include!("evaluate_tests_parts/part_03.rs");
include!("evaluate_tests_parts/part_04.rs");
include!("evaluate_tests_parts/part_05.rs");
include!("evaluate_tests_parts/part_06.rs");
include!("evaluate_tests_parts/part_07.rs");
include!("evaluate_tests_parts/part_08.rs");
include!("evaluate_tests_parts/part_09.rs");
include!("evaluate_tests_parts/part_10.rs");
include!("evaluate_tests_parts/part_11.rs");
include!("evaluate_tests_parts/part_12.rs");
include!("evaluate_tests_parts/part_13.rs");
include!("evaluate_tests_parts/part_14.rs");
include!("evaluate_tests_parts/part_15.rs");
include!("evaluate_tests_parts/part_16.rs");
include!("evaluate_tests_parts/part_17.rs");
include!("evaluate_tests_parts/part_18.rs");
include!("evaluate_tests_parts/part_19.rs");
include!("evaluate_tests_parts/part_20.rs");
include!("evaluate_tests_parts/part_21.rs");
include!("evaluate_tests_parts/part_22.rs");
include!("evaluate_tests_parts/part_23.rs");
include!("evaluate_tests_parts/part_24.rs");
