pub mod class_type;
pub mod computation;
pub mod function_iife_inference;
pub mod function_type;
pub(crate) mod function_type_circular;
pub(crate) mod function_type_helpers;
pub(crate) mod function_type_signature_display;
pub mod interface_type;
pub mod module_augmentation;
pub mod object_type;
mod property_access_augmentation;
pub(crate) mod property_access_helpers;
mod property_access_narrowing_skip;
pub(crate) mod property_access_type;
pub(crate) mod queries;
pub mod type_checking;
pub mod type_literal_checker;
pub mod type_node;
mod type_node_advanced;
mod type_node_context;
pub(crate) mod type_node_helpers;
mod type_node_lowering;
mod type_node_merged_value_query;
mod type_node_property_names;
mod type_node_query_members;
mod type_node_resolution;
pub(crate) mod unique_symbol_arena;
pub(crate) mod utilities;
pub(crate) mod window_global_this_annotation;
