pub mod class_type;
pub mod computation;
pub mod function_iife_inference;
pub mod function_type;
pub(crate) mod function_type_circular;
pub(crate) mod function_type_helpers;
pub(crate) mod function_type_signature_display;
pub mod interface_type;
pub mod literal_type;
pub mod object_type;
pub(crate) mod property_access_helpers;
pub(crate) mod property_access_type;
pub(crate) mod queries;
pub mod type_checking;
pub mod type_literal_checker;
pub mod type_node;
mod type_node_helpers;
mod type_node_resolution;
pub(crate) mod utilities;
