use std::path::Path;
use std::sync::Arc;

use crate::{
    CompileExitStatus, CompileOutput, Compiler, CompilerOptions, SemanticCompletion, SourceInput,
};

// Expected products were generated by the pinned TypeScript 7.0.2 native oracle with
// `--singleThreaded --stableTypeOrdering true --declaration --noCheck` and the target named by
// each test.

fn compile(sources: &[(&str, &str)], target: &str) -> CompileOutput {
    Compiler::new().compile(
        sources
            .iter()
            .map(|(path, source)| SourceInput::new(*path, Arc::<str>::from(*source)))
            .collect(),
        &CompilerOptions {
            declaration: true,
            module: "esnext".to_string(),
            target: target.to_string(),
            no_check: true,
            ..CompilerOptions::default()
        },
    )
}

fn assert_complete_with_paths(output: &CompileOutput, expected_paths: &[&str]) {
    assert!(output.diagnostics.is_empty(), "{:#?}", output.diagnostics);
    assert_eq!(output.semantic_completion, SemanticCompletion::Complete);
    assert_eq!(output.exit_status, CompileExitStatus::Success);
    assert_eq!(
        output
            .emitted_files
            .iter()
            .map(|file| file.path.to_string_lossy().into_owned())
            .collect::<Vec<_>>(),
        expected_paths,
    );
}

fn product<'a>(output: &'a CompileOutput, path: &str) -> &'a str {
    &output
        .emitted_files
        .iter()
        .find(|file| file.path == Path::new(path))
        .unwrap_or_else(|| panic!("missing exact emit product {path}"))
        .text
}

#[test]
fn es2017_preserves_async_functions_and_visibility_varied_class_methods() {
    let source = concat!(
        "export async function resolveValue(input: number): Promise<number> {\n",
        "    return input;\n",
        "}\n",
        "export class AsyncBoundary {\n",
        "    public async exposed(value: number): Promise<number> { return value; }\n",
        "    protected async guarded(value: number): Promise<number> { return value; }\n",
        "    static async shared(value: number): Promise<number> { return value; }\n",
        "}\n",
    );
    let output = compile(
        &[
            ("async-boundary.ts", source),
            ("stable.ts", "export const stable: number = 1;\n"),
        ],
        "es2017",
    );

    assert_complete_with_paths(
        &output,
        &[
            "async-boundary.d.ts",
            "async-boundary.js",
            "stable.d.ts",
            "stable.js",
        ],
    );
    assert_eq!(
        product(&output, "async-boundary.js"),
        concat!(
            "export async function resolveValue(input) {\n",
            "    return input;\n",
            "}\n",
            "export class AsyncBoundary {\n",
            "    async exposed(value) {\n",
            "        return value;\n",
            "    }\n",
            "    async guarded(value) {\n",
            "        return value;\n",
            "    }\n",
            "    static async shared(value) {\n",
            "        return value;\n",
            "    }\n",
            "}\n",
        ),
    );
    assert_eq!(
        product(&output, "async-boundary.d.ts"),
        concat!(
            "export declare function resolveValue(input: number): Promise<number>;\n",
            "export declare class AsyncBoundary {\n",
            "    exposed(value: number): Promise<number>;\n",
            "    protected guarded(value: number): Promise<number>;\n",
            "    static shared(value: number): Promise<number>;\n",
            "}\n",
        ),
    );
    assert_eq!(product(&output, "stable.js"), "export const stable = 1;\n");
    assert_eq!(
        product(&output, "stable.d.ts"),
        "export declare const stable: number;\n",
    );
}

#[test]
fn es2022_preserves_named_and_private_instance_and_static_class_elements() {
    let source = concat!(
        "export class NativeElements {\n",
        "    namedInitialized: number = 1;\n",
        "    namedPending: number;\n",
        "    static namedStaticInitialized: number = 2;\n",
        "    static namedStaticPending: number;\n",
        "    #privateInitialized: number = 3;\n",
        "    #privatePending: number;\n",
        "    static #privateStaticInitialized: number = 4;\n",
        "    static #privateStaticPending: number;\n",
        "    #method(value: number): number { return value; }\n",
        "    static #staticMethod(value: number): number { return value; }\n",
        "    get #accessor(): number { return 1; }\n",
        "    set #accessor(value: number) {}\n",
        "    static get #staticAccessor(): number { return 2; }\n",
        "    static set #staticAccessor(value: number) {}\n",
        "}\n",
    );
    let output = compile(&[("native-elements.ts", source)], "es2022");

    assert_complete_with_paths(&output, &["native-elements.d.ts", "native-elements.js"]);
    assert_eq!(
        product(&output, "native-elements.js"),
        concat!(
            "export class NativeElements {\n",
            "    namedInitialized = 1;\n",
            "    namedPending;\n",
            "    static namedStaticInitialized = 2;\n",
            "    static namedStaticPending;\n",
            "    #privateInitialized = 3;\n",
            "    #privatePending;\n",
            "    static #privateStaticInitialized = 4;\n",
            "    static #privateStaticPending;\n",
            "    #method(value) {\n",
            "        return value;\n",
            "    }\n",
            "    static #staticMethod(value) {\n",
            "        return value;\n",
            "    }\n",
            "    get #accessor() {\n",
            "        return 1;\n",
            "    }\n",
            "    set #accessor(value) { }\n",
            "    static get #staticAccessor() {\n",
            "        return 2;\n",
            "    }\n",
            "    static set #staticAccessor(value) { }\n",
            "}\n",
        ),
    );
    assert_eq!(
        product(&output, "native-elements.d.ts"),
        concat!(
            "export declare class NativeElements {\n",
            "    #private;\n",
            "    namedInitialized: number;\n",
            "    namedPending: number;\n",
            "    static namedStaticInitialized: number;\n",
            "    static namedStaticPending: number;\n",
            "}\n",
        ),
    );
}

#[test]
fn es2015_preserves_runtime_accessors_and_erases_types_and_visibility() {
    let source = concat!(
        "export class RuntimeAccessors {\n",
        "    public get exposed(): number { return 1; }\n",
        "    public set exposed(next: number) {}\n",
        "    protected get guarded(): string { return \"guarded\"; }\n",
        "    protected set guarded(candidate: string) {}\n",
        "    private get hidden(): boolean { return true; }\n",
        "    private set hidden(secret: boolean) {}\n",
        "    static get shared(): number { return 2; }\n",
        "    static set shared(value: number) {}\n",
        "}\n",
    );
    let output = compile(&[("runtime-accessors.ts", source)], "es2015");

    assert_complete_with_paths(&output, &["runtime-accessors.d.ts", "runtime-accessors.js"]);
    assert_eq!(
        product(&output, "runtime-accessors.js"),
        concat!(
            "export class RuntimeAccessors {\n",
            "    get exposed() {\n",
            "        return 1;\n",
            "    }\n",
            "    set exposed(next) { }\n",
            "    get guarded() {\n",
            "        return \"guarded\";\n",
            "    }\n",
            "    set guarded(candidate) { }\n",
            "    get hidden() {\n",
            "        return true;\n",
            "    }\n",
            "    set hidden(secret) { }\n",
            "    static get shared() {\n",
            "        return 2;\n",
            "    }\n",
            "    static set shared(value) { }\n",
            "}\n",
        ),
    );
    assert_eq!(
        product(&output, "runtime-accessors.d.ts"),
        concat!(
            "export declare class RuntimeAccessors {\n",
            "    get exposed(): number;\n",
            "    set exposed(next: number);\n",
            "    protected get guarded(): string;\n",
            "    protected set guarded(candidate: string);\n",
            "    private get hidden();\n",
            "    private set hidden(value);\n",
            "    static get shared(): number;\n",
            "    static set shared(value: number);\n",
            "}\n",
        ),
    );
}
