name: 'AI Orchestrator'
description: 'Orchestrate AI tasks using Claude Code'

inputs:
  goal:
    description: 'The high-level goal to achieve'
    required: true
  mode:
    description: 'Mode: run (full loop), plan, work, review, merge'
    default: 'run'
  branch:
    description: 'Base branch for changes'
    default: 'main'
  anthropic_api_key:
    description: 'Anthropic API key'
    required: true
  github_token:
    description: 'GitHub token for PRs'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Claude Code
      shell: bash
      run: npm install -g @anthropic-ai/claude-code

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run Orchestrator
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        chmod +x ${{ github.action_path }}/orchestrator.sh
        ${{ github.action_path }}/orchestrator.sh "${{ inputs.mode }}" "${{ inputs.goal }}" "${{ inputs.branch }}"
