export const PROJECT_ROW_DEFINITIONS = [
  {
    name: "utility-types-project",
    label: "utility-types",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 5",
    family: "baseline utility mapped/conditional surface",
    fixture_dir: "utility-types",
    source_dir: "src",
    repo_env: "UTILITY_TYPES_REPO",
    ref_env: "UTILITY_TYPES_REF",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "ts-essentials-project",
    label: "ts-essentials",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 5",
    family: "utility types plus recursive JSON shapes",
    fixture_dir: "ts-essentials",
    source_dir: "lib",
    repo_env: "TS_ESSENTIALS_REPO",
    ref_env: "TS_ESSENTIALS_REF",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "rxjs-project",
    label: "RxJS",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 3, 7, 10",
    family: "observable/subject generics, module identity, generated config pressure",
    fixture_dir: "rxjs",
    source_dir: "src/internal",
    repo_env: "RXJS_REPO",
    ref_env: "RXJS_REF",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "type-fest-project",
    label: "type-fest",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 5",
    family: "mapped/conditional/key-space utility surface",
    fixture_dir: "type-fest",
    source_dir: "source",
    repo_env: "TYPE_FEST_REPO",
    ref_env: "TYPE_FEST_REF",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "ts-toolbelt-project",
    label: "ts-toolbelt",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 3",
    family: "recursive type evaluation pressure",
    fixture_dir: "ts-toolbelt",
    source_dir: "sources",
    repo_env: "TS_TOOLBELT_REPO",
    ref_env: "TS_TOOLBELT_REF",
    guard_set: "canary",
    benchmark_set: "canary",
    category: "external",
  },
  {
    name: "zod-project",
    label: "Zod",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 4, 6, 7",
    family: "recursive conditionals, object guards, class/generic identity",
    fixture_dir: "zod",
    source_dir: "src",
    repo_env: "ZOD_REPO",
    ref_env: "ZOD_REF",
    guard_set: "canary",
    benchmark_set: "canary",
    category: "external",
  },
  {
    name: "kysely-project",
    label: "Kysely",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 3, 5, 6",
    family: "contextual generics, guards, indexed/property access",
    fixture_dir: "kysely",
    source_dir: "src",
    repo_env: "KYSELY_REPO",
    ref_env: "KYSELY_REF",
    guard_set: "canary",
    benchmark_set: "canary",
    category: "external",
  },
  {
    name: "type-challenges-project",
    label: "type-challenges",
    readme_candidates: ["README.md"],
    owner: "Tracks 2, 3, 5",
    family: "advanced type-level challenge templates",
    fixture_dir: "type-challenges",
    source_dir: "questions",
    repo_env: "TYPE_CHALLENGES_REPO",
    ref_env: "TYPE_CHALLENGES_REF",
    guard_set: "canary",
    benchmark_set: "canary",
    category: "generated",
  },
  {
    name: "type-challenges-solutions-project",
    label: "type-challenges solutions",
    readme_candidates: ["README.md"],
    owner: "Tracks 2, 3, 5",
    family: "advanced type-level solved challenge programs",
    fixture_dir: "type-challenges-solutions",
    source_dir: "solutions",
    repo_env: "TYPE_CHALLENGES_SOLUTIONS_REPO",
    ref_env: "TYPE_CHALLENGES_SOLUTIONS_REF",
    guard_set: "canary",
    benchmark_set: "canary",
    category: "generated",
  },
  {
    name: "vite-vanilla-ts-app",
    label: "generated Vite app",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 9",
    family: "generated app dependency/config sanity",
    fixture_dir: "vite-vanilla-ts-live",
    source_dir: "src",
    guard_set: null,
    benchmark_set: "required",
    category: "generated",
  },
  {
    name: "nextjs-fresh-app",
    label: "generated Next app",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 9",
    family: "generated app-router dependency/config sanity",
    fixture_dir: "next-app-live",
    source_dir: ".",
    guard_set: null,
    benchmark_set: "required",
    category: "generated",
  },
  {
    name: "large-ts-repo",
    label: "large-ts-repo",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 10",
    family: "residency/runtime/project graph stress",
    fixture_dir: "large-ts-repo",
    source_dir: "packages",
    guard_set: null,
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "nextjs",
    label: "Next.js full project",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 9",
    family: "module graph plus generated app dependencies",
    fixture_dir: "next.js",
    source_dir: "packages/next/src",
    guard_set: null,
    benchmark_set: "required",
    category: "external",
  },
];

export const REQUIRED_PROJECT_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.benchmark_set === "required")
  .map((row) => row.name);

export const COMPILE_GUARD_REQUIRED_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.guard_set === "required")
  .map((row) => row.name);

export const COMPILE_CANARY_PROJECT_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.guard_set === "canary")
  .map((row) => row.name);

export const COMPILE_GUARD_CANARY_PROJECT_ROWS = COMPILE_CANARY_PROJECT_ROWS;

export const PROJECT_ROWS_BY_NAME = Object.fromEntries(
  PROJECT_ROW_DEFINITIONS.map((row) => [row.name, row])
);

export const REQUIRED_COMPATIBILITY_FIELDS = [
  "state",
  "exit_class",
  "first_failure_class",
  "owner_track",
  "phase",
  "last_successful_phase",
  "diagnostic_status",
  "diagnostic_deltas",
  "diagnostic_subsystems",
  "known_blockers",
  "reduced_repro_path",
  "repro",
  "exit_codes",
  "files_reached",
  "peak_memory_bytes",
  "fixture_sources",
  "emit_status",
  "dts_status",
];
export const COMPATIBILITY_CORPUS_ROWS = PROJECT_ROW_DEFINITIONS.map((row) => ({
  name: row.name,
  label: row.label,
  owner: row.owner,
  family: row.family,
  readme_candidates: row.readme_candidates,
}));
