export const PROJECT_ROW_DEFINITIONS = [
  {
    name: "utility-types-project",
    label: "utility-types",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 5",
    family: "baseline utility mapped/conditional surface",
    fixture_dir: "utility-types",
    source_dir: "src",
    repo_env: "UTILITY_TYPES_REPO",
    ref_env: "UTILITY_TYPES_REF",
    repo: "https://github.com/piotrwitek/utility-types.git",
    ref: "2ee1f6ecb241651ab22390fee7ee5349942efda2",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "ts-essentials-project",
    label: "ts-essentials",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 5",
    family: "utility types plus recursive JSON shapes",
    fixture_dir: "ts-essentials",
    source_dir: "lib",
    repo_env: "TS_ESSENTIALS_REPO",
    ref_env: "TS_ESSENTIALS_REF",
    repo: "https://github.com/ts-essentials/ts-essentials.git",
    ref: "5abe8700b42068048bd3c368e0531b6defe56558",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "rxjs-project",
    label: "RxJS",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 3, 7, 10",
    family: "observable/subject generics, module identity, generated config pressure",
    fixture_dir: "rxjs",
    source_dir: "src/internal",
    repo_env: "RXJS_REPO",
    ref_env: "RXJS_REF",
    repo: "https://github.com/ReactiveX/rxjs.git",
    ref: "e5351d02e225e275ac0e497c7b66eaa5f0c88791",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "type-fest-project",
    label: "type-fest",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 5",
    family: "mapped/conditional/key-space utility surface",
    fixture_dir: "type-fest",
    source_dir: "source",
    repo_env: "TYPE_FEST_REPO",
    ref_env: "TYPE_FEST_REF",
    repo: "https://github.com/sindresorhus/type-fest.git",
    ref: "4005f60b65a7bd224154d6da46f45a63b42ce70f",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "ts-toolbelt-project",
    label: "ts-toolbelt",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 3",
    family: "recursive type evaluation pressure",
    fixture_dir: "ts-toolbelt",
    source_dir: "sources",
    repo_env: "TS_TOOLBELT_REPO",
    ref_env: "TS_TOOLBELT_REF",
    repo: "https://github.com/millsp/ts-toolbelt.git",
    ref: "b8a49285e3ed3a7d8bb8e0b433389eac46a5f140",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "zod-project",
    label: "Zod",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 4, 6, 7",
    family: "recursive conditionals, object guards, class/generic identity",
    fixture_dir: "zod",
    source_dir: "src",
    repo_env: "ZOD_REPO",
    ref_env: "ZOD_REF",
    repo: "https://github.com/colinhacks/zod.git",
    ref: "93b0b6892cc0cfee8d0bec4e2e1242c7df771f95",
    guard_set: "canary",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "kysely-project",
    label: "Kysely",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 3, 5, 6",
    family: "contextual generics, guards, indexed/property access",
    fixture_dir: "kysely",
    source_dir: "src",
    repo_env: "KYSELY_REPO",
    ref_env: "KYSELY_REF",
    repo: "https://github.com/kysely-org/kysely.git",
    ref: "d4911be21cd568d3694dc7f879f72390635226d7",
    guard_set: "canary",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "type-challenges-solutions-project",
    label: "type-challenges solutions",
    readme_candidates: ["README.md"],
    owner: "Tracks 2, 3, 5",
    family: "advanced type-level solved challenge programs",
    fixture_dir: "type-challenges-solutions",
    source_dir: "solutions",
    repo_env: "TYPE_CHALLENGES_SOLUTIONS_REPO",
    ref_env: "TYPE_CHALLENGES_SOLUTIONS_REF",
    repo: "https://github.com/ghaiklor/type-challenges-solutions.git",
    ref: "91a6d2986650475f29eeb3bd18ebd025128aa07e",
    expected_generated: 78,
    expected_generated_env: "TYPE_CHALLENGES_SOLUTIONS_EXPECTED_GENERATED",
    guard_set: "required",
    benchmark_set: "required",
    category: "generated",
  },
  {
    name: "vite-vanilla-ts-app",
    label: "generated Vite app",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 9",
    family: "generated app dependency/config sanity",
    fixture_dir: "vite-vanilla-ts-live",
    source_dir: "src",
    guard_set: "required",
    benchmark_set: "required",
    category: "generated",
    generated_by: "scripts/bench/generate-vite-app-fixture.mjs",
  },
  {
    name: "nextjs-fresh-app",
    label: "generated Next app",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 9",
    family: "generated app-router dependency/config sanity",
    fixture_dir: "next-app-live",
    source_dir: ".",
    guard_set: "required",
    benchmark_set: "required",
    category: "generated",
    generated_by: "scripts/bench/generate-next-app-fixture.mjs",
  },
  {
    name: "large-ts-repo",
    label: "large-ts-repo",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 10",
    family: "residency/runtime/project graph stress",
    fixture_dir: "large-ts-repo",
    source_dir: "packages",
    repo_env: "LARGE_TS_REPO",
    ref_env: "LARGE_TS_REF",
    repo: "https://github.com/mohsen1/large-ts-repo.git",
    ref: "e1b22bda18664a507ed0da19c155e0365d585b18",
    guard_set: null,
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "nextjs",
    label: "Next.js full project",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 9",
    family: "module graph plus generated app dependencies",
    fixture_dir: "next.js",
    source_dir: "packages/next/src",
    repo_env: "NEXTJS_REPO",
    ref_env: "NEXTJS_REF",
    repo: "https://github.com/vercel/next.js.git",
    ref: "09851e208cc62c8b6fe7a953b42c88e843129178",
    guard_set: null,
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "valibot-project",
    label: "Valibot",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 5",
    family: "schema-builder generics with recursive conditionals",
    fixture_dir: "valibot",
    source_dir: "library/src",
    repo_env: "VALIBOT_REPO",
    ref_env: "VALIBOT_REF",
    repo: "https://github.com/fabian-hiller/valibot.git",
    ref: "e7bcacb107b1c5a74dfd564babd2c8697037ee06",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "msw-project",
    label: "MSW",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7, 9",
    family: "pnpm-symlinked @types graph plus project references",
    fixture_dir: "msw",
    source_dir: "src",
    repo_env: "MSW_REPO",
    ref_env: "MSW_REF",
    repo: "https://github.com/mswjs/msw.git",
    ref: "8a19d5485adad2b8a816e04a937f4c76169cd5b9",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "comlink-project",
    label: "Comlink",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7",
    family: "small strict node10 baseline, lib-catalog coverage canary",
    fixture_dir: "comlink",
    source_dir: "src",
    repo_env: "COMLINK_REPO",
    ref_env: "COMLINK_REF",
    repo: "https://github.com/GoogleChromeLabs/comlink.git",
    ref: "114a4a6448a855a613f1cb9a7c89290606c003cf",
    guard_set: "required",
    benchmark_set: "required",
    category: "external",
  },
  {
    name: "effect-project",
    label: "Effect",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 5, 7",
    family: "large-scale schema/effect generics, ~296k LOC parity canary",
    fixture_dir: "effect",
    source_dir: "packages/effect/src",
    repo_env: "EFFECT_REPO",
    ref_env: "EFFECT_REF",
    repo: "https://github.com/Effect-TS/effect.git",
    ref: "626c61b3ef0dce59ffb038590bc834d36afc5d1d",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "drizzle-orm-project",
    label: "Drizzle ORM",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 6, 7",
    family: "JSON file routing + contextual-keyword binders + pnpm @types graph",
    fixture_dir: "drizzle-orm",
    source_dir: "drizzle-orm/src",
    repo_env: "DRIZZLE_ORM_REPO",
    ref_env: "DRIZZLE_ORM_REF",
    repo: "https://github.com/drizzle-team/drizzle-orm.git",
    ref: "48e5406027103a9fca6eb66417187c4a8b5c6aa3",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "ts-rest-project",
    label: "ts-rest",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2, 5",
    family: "API contract generics over zod + http schemas, near-clean parity",
    fixture_dir: "ts-rest",
    source_dir: "libs/ts-rest/core/src",
    repo_env: "TS_REST_REPO",
    ref_env: "TS_REST_REF",
    repo: "https://github.com/ts-rest/ts-rest.git",
    ref: "dd7239bc950d1e254d9c9cd6df7dbccc529c33cb",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "ofetch-project",
    label: "ofetch",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 7",
    family: "small fetch wrapper, single-diagnostic canary for TS5107 chain rule",
    fixture_dir: "ofetch",
    source_dir: "src",
    repo_env: "OFETCH_REPO",
    ref_env: "OFETCH_REF",
    repo: "https://github.com/unjs/ofetch.git",
    ref: "dfbe3ca4ef8a22fc023fca5a5ef530e525f5e523",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "ts-pattern-project",
    label: "ts-pattern",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2",
    family: "exhaustive pattern-matching union distribution/negation; canary for symbol-keyed computed-property members from a value/type name-merge",
    fixture_dir: "ts-pattern",
    source_dir: "src",
    repo_env: "TS_PATTERN_REPO",
    ref_env: "TS_PATTERN_REF",
    repo: "https://github.com/gvergnaud/ts-pattern.git",
    ref: "c92ca435c7e1827e0fd55c539080ef1bfd6fe3f0",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "radash-project",
    label: "radash",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2",
    family: "zero-dependency functional utility belt; canary for cross-file context-dependent FPs (#14344 identity/relation family) — clean per-file, fires only on whole-project compile",
    fixture_dir: "radash",
    source_dir: "src",
    repo_env: "RADASH_REPO",
    ref_env: "RADASH_REF",
    repo: "https://github.com/sodiray/radash.git",
    ref: "4cab1900d08e0997abc4f17aec3cbfe18958d766",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "valtio-project",
    label: "valtio",
    readme_candidates: ["readme.md", "README.md"],
    owner: "Tracks 1, 2",
    family: "proxy-state reactive store; canary for cross-file context-dependent FPs (#14344 identity/relation family) — clean per-file, fires only on whole-project compile",
    fixture_dir: "valtio",
    source_dir: "src",
    repo_env: "VALTIO_REPO",
    ref_env: "VALTIO_REF",
    repo: "https://github.com/pmndrs/valtio.git",
    ref: "c24a93a1b62d1fb95a7fa78c840d32cf95bef348",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "scule-project",
    label: "scule",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2",
    family: "string-casing utility belt (camelCase/PascalCase/kebab); clean green row — tsz byte-parity-clean vs tsc (both 0 errors) on the whole-project compile",
    fixture_dir: "scule",
    source_dir: "src",
    repo_env: "SCULE_REPO",
    ref_env: "SCULE_REF",
    repo: "https://github.com/unjs/scule.git",
    ref: "5bc68048caad7c0e7de35842c83a510e8e1a7c4f",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "mitt-project",
    label: "mitt",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2",
    family: "tiny functional event emitter; clean green row — tsz byte-parity-clean vs tsc (both 0 errors) on the whole-project compile",
    fixture_dir: "mitt",
    source_dir: "src",
    repo_env: "MITT_REPO",
    ref_env: "MITT_REF",
    repo: "https://github.com/developit/mitt.git",
    ref: "6b41670516ed8e8b738612f60491995470aa63b3",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "change-case-project",
    label: "change-case",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "string-casing utility belt (camelCase/PascalCase/kebab/snake); ~332 lines of real `.ts` (`packages/change-case/src/index.ts` + `keys.ts`, `*.spec.ts` excluded) — clean green row, tsz byte-parity-clean vs tsc (both 0 errors) on the whole-project compile",
    fixture_dir: "change-case",
    source_dir: "packages/change-case/src",
    repo_env: "CHANGE_CASE_REPO",
    ref_env: "CHANGE_CASE_REF",
    repo: "https://github.com/blakeembrey/change-case.git",
    ref: "9d5505c7e807544a18d98052802985069ac190d0",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "tiny-invariant-project",
    label: "tiny-invariant",
    readme_candidates: ["README.md"],
    owner: "Tracks 1, 2",
    family: "tiny runtime invariant assertion helper; clean green row — tsz byte-parity-clean vs tsc (both emit only the shared TS2591 process baseline line, 0 tsz-only delta) on the whole-project compile",
    fixture_dir: "tiny-invariant",
    source_dir: "src",
    repo_env: "TINY_INVARIANT_REPO",
    ref_env: "TINY_INVARIANT_REF",
    repo: "https://github.com/alexreardon/tiny-invariant.git",
    ref: "b5587cf4ba45e257bce49053c3345b6614324252",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "ts-belt-project",
    label: "ts-belt",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "zero-dependency functional utility belt; first-blocker = named-import of a global type through a `/// <reference>`-bearing module reported TS2305 (export-resolution divergence — bounded, tsz-only, repros standalone)",
    fixture_dir: "ts-belt",
    source_dir: "src",
    repo_env: "TS_BELT_REPO",
    ref_env: "TS_BELT_REF",
    repo: "https://github.com/mobily/ts-belt.git",
    ref: "c825d9709de1e5d15b1b362429e0cee56c96c516",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "ts-extras-project",
    label: "ts-extras",
    readme_candidates: ["readme.md", "README.md"],
    owner: "Tracks 1, 2",
    family: "type-fest-based assertion/guard helpers; fully tsc-parity under the guard config (tsz-only delta = 0). NOTE: type-fest is unresolved under the shared `types: []` baseline (its TS2307 cancels in both tsz and tsc), so the type-fest-typed paths are any-stubbed — a thin parity row, not a deep witness",
    fixture_dir: "ts-extras",
    source_dir: "source",
    repo_env: "TS_EXTRAS_REPO",
    ref_env: "TS_EXTRAS_REF",
    repo: "https://github.com/sindresorhus/ts-extras.git",
    ref: "1e886239c7f7010c1cfa194e13d4d123b160cbb3",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "superjson-project",
    label: "superjson",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "JSON (de)serialization with type metadata; first-blocker = cross-file context-dependent FP cluster (#14344 identity/relation family) in transformer.ts/plainer.ts — fires only on whole-project compile",
    fixture_dir: "superjson",
    source_dir: "src",
    repo_env: "SUPERJSON_REPO",
    ref_env: "SUPERJSON_REF",
    repo: "https://github.com/flightcontrolhq/superjson.git",
    ref: "aaa65e36e8e31da740265a56b27c965ca1c7b754",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "trpc-project",
    label: "tRPC",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 3",
    family: "end-to-end inference: recursive router builders, deep generic procedure chaining, input/output type propagation",
    fixture_dir: "trpc",
    source_dir: "packages/server/src",
    repo_env: "TRPC_REPO",
    ref_env: "TRPC_REF",
    repo: "https://github.com/trpc/trpc.git",
    ref: "f8f0c0e3979ecb980d38e9369fa8c98df95d212b",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "tanstack-query-project",
    label: "TanStack Query",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "query/mutation generic option bags, overloaded hook signatures, key/data inference",
    fixture_dir: "tanstack-query",
    source_dir: "packages/query-core/src",
    repo_env: "TANSTACK_QUERY_REPO",
    ref_env: "TANSTACK_QUERY_REF",
    repo: "https://github.com/TanStack/query.git",
    ref: "feb1efd804c1262106f72c8adc1d82a8ce9cfbb0",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "tanstack-router-project",
    label: "TanStack Router",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "template-literal route path parsing, nested route-tree generics, search-param inference",
    fixture_dir: "tanstack-router",
    source_dir: "packages/router-core/src",
    repo_env: "TANSTACK_ROUTER_REPO",
    ref_env: "TANSTACK_ROUTER_REF",
    repo: "https://github.com/TanStack/router.git",
    ref: "36ed57409a98878e5c1a7aabf50d3aa65ebde1e0",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "zustand-project",
    label: "Zustand",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "store middleware generic composition, slice typing, set/get state inference",
    fixture_dir: "zustand",
    source_dir: "src",
    repo_env: "ZUSTAND_REPO",
    ref_env: "ZUSTAND_REF",
    repo: "https://github.com/pmndrs/zustand.git",
    ref: "566b5bf448f4354eb8e35c6243ea3772bdb3be96",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "jotai-project",
    label: "Jotai",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "atom generic families, derived/async atom inference, store typing",
    fixture_dir: "jotai",
    source_dir: "src",
    repo_env: "JOTAI_REPO",
    ref_env: "JOTAI_REF",
    repo: "https://github.com/pmndrs/jotai.git",
    ref: "ddd36007f99903a2258ee47bcd4490ad4589602e",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "fp-ts-project",
    label: "fp-ts",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 3",
    family: "higher-kinded type encoding, type-class hierarchies, deep generic pipe/flow composition",
    fixture_dir: "fp-ts",
    source_dir: "src",
    repo_env: "FP_TS_REPO",
    ref_env: "FP_TS_REF",
    repo: "https://github.com/gcanti/fp-ts.git",
    ref: "c0a6472121c67a2b083e62fcff13e7d022e39d8f",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "io-ts-project",
    label: "io-ts",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "codec generics, recursive/branded runtime type definitions, decode-result inference",
    fixture_dir: "io-ts",
    source_dir: "src",
    repo_env: "IO_TS_REPO",
    ref_env: "IO_TS_REF",
    repo: "https://github.com/gcanti/io-ts.git",
    ref: "864a3a2f03c5d7b974afeb1da0faf46c21758779",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "immer-project",
    label: "Immer",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "recursive Draft<T> mapped/conditional readonly stripping, produce overloads",
    fixture_dir: "immer",
    source_dir: "src",
    repo_env: "IMMER_REPO",
    ref_env: "IMMER_REF",
    repo: "https://github.com/immerjs/immer.git",
    ref: "bf2d15439259887f98f2737cf7ebde4234d5adea",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "remeda-project",
    label: "Remeda",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "data-first/data-last overload resolution, purry typing, large utility surface",
    fixture_dir: "remeda",
    source_dir: "packages/remeda/src",
    repo_env: "REMEDA_REPO",
    ref_env: "REMEDA_REF",
    repo: "https://github.com/remeda/remeda.git",
    ref: "53d22a60dcd1f854a6d7d7498715ba6f4f56473f",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "ts-morph-project",
    label: "ts-morph",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 3",
    family: "large AST wrapper class hierarchy, compiler-API generic surface, declaration-heavy graph",
    fixture_dir: "ts-morph",
    source_dir: "packages/ts-morph/src",
    repo_env: "TS_MORPH_REPO",
    ref_env: "TS_MORPH_REF",
    repo: "https://github.com/dsherret/ts-morph.git",
    ref: "699815f54ae9b5c2a93f016ba1a9df1e8ac1c014",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "arktype-project",
    label: "ArkType",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 3",
    family: "type-level string parser, recursive schema inference, extreme conditional/template evaluation",
    fixture_dir: "arktype",
    source_dir: "ark/type",
    repo_env: "ARKTYPE_REPO",
    ref_env: "ARKTYPE_REF",
    repo: "https://github.com/arktypeio/arktype.git",
    ref: "d075962caee162bb28e241723863e8f11cb58390",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "superstruct-project",
    label: "Superstruct",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "struct combinator generics, recursive object validation typing",
    fixture_dir: "superstruct",
    source_dir: "src",
    repo_env: "SUPERSTRUCT_REPO",
    ref_env: "SUPERSTRUCT_REF",
    repo: "https://github.com/ianstormtaylor/superstruct.git",
    ref: "e414c8afd3b69f6bc0173b8ee25f71d8e5694f01",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "runtypes-project",
    label: "Runtypes",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "runtime type combinator generics, static type extraction, recursive records",
    fixture_dir: "runtypes",
    source_dir: "src",
    repo_env: "RUNTYPES_REPO",
    ref_env: "RUNTYPES_REF",
    repo: "https://github.com/runtypes/runtypes.git",
    ref: "16d83ca56a54569e4a2375a965567b31191c0035",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "hotscript-project",
    label: "HotScript",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 3",
    family: "type-level lambda/HOF evaluation, deep recursive conditional/template composition",
    fixture_dir: "hotscript",
    source_dir: "src",
    repo_env: "HOTSCRIPT_REPO",
    ref_env: "HOTSCRIPT_REF",
    repo: "https://github.com/gvergnaud/hotscript.git",
    ref: "0bc205286bd5eea0b89fa903c411df9aca95923c",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "typebox-project",
    label: "TypeBox",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 3",
    family: "JSON-schema type builder, recursive static inference, large conditional/template surface",
    fixture_dir: "typebox",
    source_dir: "src",
    repo_env: "TYPEBOX_REPO",
    ref_env: "TYPEBOX_REF",
    repo: "https://github.com/sinclairzx81/typebox.git",
    ref: "22c9be6d4d26ef1feb797ffcf4f31b2c863e936b",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "class-transformer-project",
    label: "class-transformer",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 6",
    family: "decorator metadata typing, class transform generics",
    fixture_dir: "class-transformer",
    source_dir: "src",
    repo_env: "CLASS_TRANSFORMER_REPO",
    ref_env: "CLASS_TRANSFORMER_REF",
    repo: "https://github.com/typestack/class-transformer.git",
    ref: "a2734a5d154c9b0beb9a10555a04416bc371de06",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "type-graphql-project",
    label: "TypeGraphQL",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 6",
    family: "decorator + generic resolver typing, schema class hierarchy",
    fixture_dir: "type-graphql",
    source_dir: "src",
    repo_env: "TYPE_GRAPHQL_REPO",
    ref_env: "TYPE_GRAPHQL_REF",
    repo: "https://github.com/MichalLytek/type-graphql.git",
    ref: "4535c3192fd321be6bade6192f0cf8d264de9baf",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "neverthrow-project",
    label: "neverthrow",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "Result/Ok/Err generic monad chaining, combine overloads",
    fixture_dir: "neverthrow",
    source_dir: "src",
    repo_env: "NEVERTHROW_REPO",
    ref_env: "NEVERTHROW_REF",
    repo: "https://github.com/supermacro/neverthrow.git",
    ref: "5ef3a018bda74fb960e44b68fc3672635ee8037d",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "xstate-project",
    label: "XState",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 3",
    family: "state-machine config generics, template-literal event/state typing, deep recursive typegen surface",
    fixture_dir: "xstate",
    source_dir: "packages/core/src",
    repo_env: "XSTATE_REPO",
    ref_env: "XSTATE_REF",
    repo: "https://github.com/statelyai/xstate.git",
    ref: "afa374afd52dc4f05baad1ead66c977a46aa5b47",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  {
    name: "mobx-project",
    label: "MobX",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2, 6",
    family: "observable/computed generic typing, decorator + annotation surface, reaction inference",
    fixture_dir: "mobx",
    source_dir: "packages/mobx/src",
    repo_env: "MOBX_REPO",
    ref_env: "MOBX_REF",
    repo: "https://github.com/mobxjs/mobx.git",
    ref: "2a069e41024433da401f3e8b3470adf194924911",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "external",
  },
  // --- application/dashboard canary rows (category:"application") ---
  // Real apps; the guard installs their deps (install_cmd in install_root) and
  // compiles with the app's own tsconfig (app_tsconfig), then drops node_modules.
  {
    name: "umami-project",
    label: "umami",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: analytics dashboard (Next.js app, jsx + @/* path aliases)",
    fixture_dir: "umami",
    source_dir: "src",
    app_tsconfig: "tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "UMAMI_REPO",
    ref_env: "UMAMI_REF",
    repo: "https://github.com/umami-software/umami.git",
    ref: "c0ea3aefbee7a3429ee2f824b06dc4a9dbe0b7e1",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "excalidraw-project",
    label: "excalidraw",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: whiteboard editor (React)",
    fixture_dir: "excalidraw",
    source_dir: "packages/excalidraw",
    app_tsconfig: "packages/excalidraw/tsconfig.json",
    install_cmd: "yarn install --frozen-lockfile --ignore-scripts --ignore-engines",
    install_root: ".",
    repo_env: "EXCALIDRAW_REPO",
    ref_env: "EXCALIDRAW_REF",
    repo: "https://github.com/excalidraw/excalidraw.git",
    ref: "28a9b1711dc0625b8ab5d643dc871810ee13642f",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "dub-project",
    label: "dub",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: link dashboard (Next.js)",
    fixture_dir: "dub",
    source_dir: "apps/web",
    app_tsconfig: "apps/web/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "DUB_REPO",
    ref_env: "DUB_REF",
    repo: "https://github.com/dubinc/dub.git",
    ref: "fcc6e9a7e8f182da90acacf3282f8411f6aca070",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "formbricks-project",
    label: "formbricks",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: experience management dashboard (Next.js)",
    fixture_dir: "formbricks",
    source_dir: "apps/web",
    app_tsconfig: "apps/web/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "FORMBRICKS_REPO",
    ref_env: "FORMBRICKS_REF",
    repo: "https://github.com/formbricks/formbricks.git",
    ref: "8b0f5baaa55ccbda35fcfcfb68579ea3854f7605",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "typebot-project",
    label: "typebot",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: chatbot builder (Next.js)",
    fixture_dir: "typebot",
    source_dir: "apps/builder",
    app_tsconfig: "apps/builder/tsconfig.json",
    install_cmd: "bun install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "TYPEBOT_REPO",
    ref_env: "TYPEBOT_REF",
    repo: "https://github.com/baptisteArno/typebot.io.git",
    ref: "c82ac4324a61376b3de3c8b75ccfad7c03f59e7a",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "lobe-chat-project",
    label: "lobe-chat",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: AI chat app (Next.js)",
    fixture_dir: "lobe-chat",
    source_dir: "src",
    app_tsconfig: "tsconfig.json",
    install_cmd: "pnpm install --no-frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "LOBE_CHAT_REPO",
    ref_env: "LOBE_CHAT_REF",
    repo: "https://github.com/lobehub/lobe-chat.git",
    ref: "95db11309ea1b7f4d53f84adc15fa2038549e1aa",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "supabase-studio-project",
    label: "supabase-studio",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: database studio dashboard (Next.js)",
    fixture_dir: "supabase-studio",
    source_dir: "apps/studio",
    app_tsconfig: "apps/studio/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "SUPABASE_STUDIO_REPO",
    ref_env: "SUPABASE_STUDIO_REF",
    repo: "https://github.com/supabase/supabase.git",
    ref: "6a6b7c90858b6b868c6d05bd3263a957357fa84a",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "infisical-project",
    label: "infisical",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: secrets management dashboard (Next.js)",
    fixture_dir: "infisical",
    source_dir: "frontend",
    // The upstream frontend/tsconfig.json is a solution-style aggregator
    // with empty files plus project references; it resolves ZERO files under `-p`
    // (references are only followed under `-b`), so it produced a phantom
    // "0 lines, tsz 24.6x faster" benchmark. Point at the real leaf config
    // whose `include` covers frontend/src. Demoted required -> canary: this
    // is a strict React app and tsz's real behavior on it is unverified, so
    // it is advisory (like the other application rows) until proven green.
    app_tsconfig: "frontend/tsconfig.app.json",
    install_cmd: "npm ci --ignore-scripts",
    install_root: ".",
    repo_env: "INFISICAL_REPO",
    ref_env: "INFISICAL_REF",
    repo: "https://github.com/Infisical/infisical.git",
    ref: "704c8cf7e76f1ce49301a5f943e51303c0db0058",
    guard_set: "canary",
    benchmark_set: "canary",
    // Not perf-timed: this canary app compiles green for compatibility, but its
    // vs-tsgo perf benchmark errors (the merged row is `winner: "error"` with no
    // tsz/tsgo timing pair). #14478 demoted it required -> canary/advisory but
    // left perf_timed:true, so the publish gate's --require-green-project-timing-pairs
    // kept demanding a timing pair the row cannot produce, blocking ~70% of Bench
    // publishes ("1 green perf-timed project row(s) missing tsz/tsgo timing pairs:
    // infisical-project"). Compat (green/red) is still tracked via the application
    // compat gate; only the unprovable perf-timing requirement is removed.
    perf_timed: false,
    category: "application",
  },
  {
    name: "payload-project",
    label: "payload",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: headless CMS (Next.js)",
    fixture_dir: "payload",
    source_dir: "packages/payload/src",
    app_tsconfig: "packages/payload/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "PAYLOAD_REPO",
    ref_env: "PAYLOAD_REF",
    repo: "https://github.com/payloadcms/payload.git",
    ref: "29ef906ba590fd168673da827ec484a1e2a723ad",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "medusa-project",
    label: "medusa",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: e-commerce backend (Node.js)",
    fixture_dir: "medusa",
    source_dir: "packages/medusa/src",
    app_tsconfig: "packages/medusa/tsconfig.json",
    install_cmd: "yarn install --immutable --mode=skip-build",
    install_root: ".",
    repo_env: "MEDUSA_REPO",
    ref_env: "MEDUSA_REF",
    repo: "https://github.com/medusajs/medusa.git",
    ref: "38725ac274d764031b52f6f35f7951aa9b3bb2a8",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "outline-project",
    label: "outline",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: knowledge base wiki (React)",
    fixture_dir: "outline",
    source_dir: "app",
    app_tsconfig: "tsconfig.json",
    install_cmd: "yarn install --immutable --mode=skip-build",
    install_root: ".",
    repo_env: "OUTLINE_REPO",
    ref_env: "OUTLINE_REF",
    repo: "https://github.com/outline/outline.git",
    ref: "62d5c25bd3f34c8914be6f8ab219b43e51854534",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "trigger-dev-project",
    label: "trigger-dev",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: background jobs dashboard (Remix)",
    fixture_dir: "trigger-dev",
    source_dir: "apps/webapp/app",
    app_tsconfig: "apps/webapp/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "TRIGGER_DEV_REPO",
    ref_env: "TRIGGER_DEV_REF",
    repo: "https://github.com/triggerdotdev/trigger.dev.git",
    ref: "e829eddd5ecdfc622f90257cebc2ee881a8f8c10",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "joplin-project",
    label: "joplin",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: note-taking desktop app (Electron)",
    fixture_dir: "joplin",
    source_dir: "packages/app-desktop",
    app_tsconfig: "packages/app-desktop/tsconfig.json",
    install_cmd: "yarn install --immutable --mode=skip-build",
    install_root: ".",
    repo_env: "JOPLIN_REPO",
    ref_env: "JOPLIN_REF",
    repo: "https://github.com/laurent22/joplin.git",
    ref: "1106aa85be38c84f883e6663a18ec3399d4c1fbd",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "directus-project",
    label: "directus",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: data platform backend (Node.js)",
    fixture_dir: "directus",
    source_dir: "api/src",
    app_tsconfig: "api/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "DIRECTUS_REPO",
    ref_env: "DIRECTUS_REF",
    repo: "https://github.com/directus/directus.git",
    ref: "c305be58168012cfa5ae8bf3974264a61fb051d1",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "n8n-project",
    label: "n8n",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: workflow automation backend (Node.js)",
    fixture_dir: "n8n",
    source_dir: "packages/cli/src",
    app_tsconfig: "packages/cli/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "N8N_REPO",
    ref_env: "N8N_REF",
    repo: "https://github.com/n8n-io/n8n.git",
    ref: "f6afb3933a1ed086b11294fb1bfe298434375969",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "cal-com-project",
    label: "cal-com",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: scheduling dashboard (Next.js)",
    fixture_dir: "cal-com",
    source_dir: "apps/web",
    app_tsconfig: "apps/web/tsconfig.json",
    install_cmd: "yarn install --immutable --mode=skip-build",
    install_root: ".",
    repo_env: "CAL_COM_REPO",
    ref_env: "CAL_COM_REF",
    repo: "https://github.com/calcom/cal.com.git",
    ref: "561cf889abc776d8553f9c692a16c47b5d1a5a03",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "documenso-project",
    label: "documenso",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: document signing app (Remix)",
    fixture_dir: "documenso",
    source_dir: "apps/remix",
    app_tsconfig: "apps/remix/tsconfig.json",
    install_cmd: "npm install --ignore-scripts --no-audit --no-fund",
    install_root: ".",
    repo_env: "DOCUMENSO_REPO",
    ref_env: "DOCUMENSO_REF",
    repo: "https://github.com/documenso/documenso.git",
    ref: "d5ce222482c2da81a1b0e6740e7d829752ea8f7f",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "affine-project",
    label: "affine",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: knowledge workspace (React)",
    fixture_dir: "affine",
    source_dir: "packages/frontend/core/src",
    app_tsconfig: "packages/frontend/core/tsconfig.json",
    install_cmd: "yarn install --immutable --mode=skip-build",
    install_root: ".",
    repo_env: "AFFINE_REPO",
    ref_env: "AFFINE_REF",
    repo: "https://github.com/toeverything/AFFiNE.git",
    ref: "da7781a75171140fd966c6cfbe05da9f1fb111d6",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "immich-server-project",
    label: "immich-server",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: photo management backend (NestJS)",
    fixture_dir: "immich-server",
    source_dir: "server/src",
    app_tsconfig: "server/tsconfig.json",
    install_cmd: "pnpm install --frozen-lockfile --ignore-scripts",
    install_root: ".",
    repo_env: "IMMICH_SERVER_REPO",
    ref_env: "IMMICH_SERVER_REF",
    repo: "https://github.com/immich-app/immich.git",
    ref: "983a005709cb55d0fb2ba3499a05b25c2291e152",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
  {
    name: "rocketchat-project",
    label: "rocketchat",
    readme_candidates: ["README.md", "readme.md"],
    owner: "Tracks 1, 2",
    family: "real-world application: team chat platform (Meteor)",
    fixture_dir: "rocketchat",
    source_dir: "apps/meteor/client",
    app_tsconfig: "apps/meteor/tsconfig.json",
    install_cmd: "yarn install --immutable --mode=skip-build",
    install_root: ".",
    repo_env: "ROCKETCHAT_REPO",
    ref_env: "ROCKETCHAT_REF",
    repo: "https://github.com/RocketChat/Rocket.Chat.git",
    ref: "02b80089e0f65df5e01d7d3c9422cf56c3771d86",
    guard_set: "canary",
    benchmark_set: "canary",
    perf_timed: true,
    category: "application",
  },
];

export const REQUIRED_PROJECT_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.benchmark_set === "required")
  .map((row) => row.name);

export const COMPILE_GUARD_REQUIRED_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.guard_set === "required")
  .map((row) => row.name);

export const COMPILE_CANARY_PROJECT_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.guard_set === "canary")
  .map((row) => row.name);

export const COMPILE_GUARD_CANARY_PROJECT_ROWS = COMPILE_CANARY_PROJECT_ROWS;

// Project rows opted into optional vs-tsgo timing via `perf_timed: true`.
// External-library rows run in the `bench-canaries` shard; application rows run
// in the `bench-applications` shard. These optional shards produce real
// tsz_ms/tsgo_ms timings for rows that complete, but they are NOT part of the
// required artifact-readiness/publish gate. The website only promotes a
// perf-timed row onto the chart once it also checks green (see the green-compat
// filter in crates/tsz-website/src/_data/benchmark_data.js).
export const PERF_TIMED_CANARY_PROJECT_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.perf_timed === true && row.category !== "application")
  .map((row) => row.name);

export const PERF_TIMED_APPLICATION_PROJECT_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.perf_timed === true && row.category === "application")
  .map((row) => row.name);

export const PERF_TIMED_PROJECT_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.perf_timed === true)
  .map((row) => row.name);

export const PROJECT_ROWS_BY_NAME = Object.fromEntries(
  PROJECT_ROW_DEFINITIONS.map((row) => [row.name, row])
);

export const REQUIRED_COMPATIBILITY_FIELDS = [
  "generated_at",
  "source_commit",
  "workflow_name",
  "workflow_run_id",
  "workflow_run_url",
  "workflow_run_attempt",
  "run_status",
  "state",
  "exit_class",
  "first_failure_class",
  "owner_track",
  "phase",
  "last_successful_phase",
  "diagnostic_status",
  "evidence_schema",
  "evidence_status",
  "evidence_failures",
  "source_dirty",
  "source_stable",
  "source_tree_fingerprint",
  "evidence_protocol_fingerprint",
  "tsz_binary_sha256",
  "build_manifest_sha256",
  "build_inputs_sha256",
  "build_manifest_binary_sha256",
  "compile_input_fingerprint",
  "compile_input_stable",
  "oracle_fingerprint",
  "diagnostic_deltas",
  "diagnostic_subsystems",
  "known_blockers",
  "reduced_repro_path",
  "repro",
  "exit_codes",
  "files_reached",
  "files_reached_reason",
  "peak_memory_bytes",
  "peak_memory_bytes_reason",
  "fixture_sources",
  "stub_inventory_schema",
  "stubbed_modules",
  "stubbed_any_members",
  "stub_inventory_fingerprint",
  "stub_inventory_owners",
  "emit_status",
  "dts_status",
];

export const COMPATIBILITY_CORPUS_ROWS = PROJECT_ROW_DEFINITIONS
  .filter((row) => row.guard_set || row.benchmark_set)
  .map((row) => ({
    name: row.name,
    label: row.label,
    owner: row.owner,
    family: row.family,
    readme_candidates: row.readme_candidates,
  }));

// The names of every defined compatibility corpus row, kept beside its sibling
// derived name-lists so consumers (the merge advisory, the website dashboard)
// share one canonical source instead of re-deriving `.map(row => row.name)`.
export const COMPATIBILITY_CORPUS_ROW_NAMES = COMPATIBILITY_CORPUS_ROWS.map((row) => row.name);
