//! Symbol-driven completion tables shared by the completions facade.
//!
//! This module owns static keyword/global symbol lists used during suggestion
//! collection. Higher-level filtering/ranking stays in `filters`/`render`.

use super::CompletionItemKind;

/// JavaScript/TypeScript keywords for completion.
/// Matches tsserver's `globalKeywords` list.
pub(super) const KEYWORDS: &[&str] = &[
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "new",
    "null",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "implements",
    "interface",
    "let",
    "package",
    "private",
    "protected",
    "public",
    "static",
    "yield",
    "abstract",
    "as",
    "asserts",
    "any",
    "async",
    "await",
    "boolean",
    "constructor",
    "declare",
    "get",
    "infer",
    "intrinsic",
    "is",
    "keyof",
    "module",
    "namespace",
    "never",
    "out",
    "readonly",
    "require",
    "number",
    "object",
    "satisfies",
    "set",
    "string",
    "symbol",
    "type",
    "undefined",
    "unique",
    "unknown",
    "using",
    "from",
    "global",
    "bigint",
    "override",
    "of",
    "defer",
];

/// Keywords valid inside a function body (subset without top-level-only keywords).
/// Matches tsserver's `globalKeywordsInsideFunction`.
pub(super) const KEYWORDS_INSIDE_FUNCTION: &[&str] = &[
    "as",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "readonly",
    "return",
    "satisfies",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "using",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// Global variable names from lib.d.ts that should appear in completions.
/// Matches tsserver's `globalsVars` list.
pub(super) const GLOBAL_VARS: &[(&str, CompletionItemKind)] = &[
    ("Array", CompletionItemKind::Class),
    ("ArrayBuffer", CompletionItemKind::Class),
    ("Boolean", CompletionItemKind::Class),
    ("DataView", CompletionItemKind::Class),
    ("Date", CompletionItemKind::Class),
    ("Error", CompletionItemKind::Class),
    ("EvalError", CompletionItemKind::Class),
    ("Float32Array", CompletionItemKind::Class),
    ("Float64Array", CompletionItemKind::Class),
    ("Function", CompletionItemKind::Class),
    ("Infinity", CompletionItemKind::Variable),
    ("Int16Array", CompletionItemKind::Class),
    ("Int32Array", CompletionItemKind::Class),
    ("Int8Array", CompletionItemKind::Class),
    ("Intl", CompletionItemKind::Module),
    ("JSON", CompletionItemKind::Module),
    ("Map", CompletionItemKind::Class),
    ("Math", CompletionItemKind::Module),
    ("NaN", CompletionItemKind::Variable),
    ("Number", CompletionItemKind::Class),
    ("Object", CompletionItemKind::Class),
    ("Promise", CompletionItemKind::Class),
    ("Proxy", CompletionItemKind::Class),
    ("RangeError", CompletionItemKind::Class),
    ("ReferenceError", CompletionItemKind::Class),
    ("Reflect", CompletionItemKind::Module),
    ("RegExp", CompletionItemKind::Class),
    ("Set", CompletionItemKind::Class),
    ("String", CompletionItemKind::Class),
    ("Symbol", CompletionItemKind::Class),
    ("SyntaxError", CompletionItemKind::Class),
    ("TypeError", CompletionItemKind::Class),
    ("URIError", CompletionItemKind::Class),
    ("Uint16Array", CompletionItemKind::Class),
    ("Uint32Array", CompletionItemKind::Class),
    ("Uint8Array", CompletionItemKind::Class),
    ("Uint8ClampedArray", CompletionItemKind::Class),
    ("WeakMap", CompletionItemKind::Class),
    ("WeakSet", CompletionItemKind::Class),
    ("clearInterval", CompletionItemKind::Function),
    ("clearTimeout", CompletionItemKind::Function),
    ("console", CompletionItemKind::Variable),
    ("decodeURI", CompletionItemKind::Function),
    ("decodeURIComponent", CompletionItemKind::Function),
    ("encodeURI", CompletionItemKind::Function),
    ("encodeURIComponent", CompletionItemKind::Function),
    ("escape", CompletionItemKind::Function),
    ("eval", CompletionItemKind::Function),
    ("globalThis", CompletionItemKind::Variable),
    ("isFinite", CompletionItemKind::Function),
    ("isNaN", CompletionItemKind::Function),
    ("parseFloat", CompletionItemKind::Function),
    ("parseInt", CompletionItemKind::Function),
    ("queueMicrotask", CompletionItemKind::Function),
    ("setInterval", CompletionItemKind::Function),
    ("setTimeout", CompletionItemKind::Function),
    ("undefined", CompletionItemKind::Variable),
    ("unescape", CompletionItemKind::Function),
];

/// Global variables that are deprecated. These get kindModifiers "deprecated,declare"
/// and sort text prefixed with "z" to push them to the end of the completion list.
pub(super) const DEPRECATED_GLOBALS: &[&str] = &["escape", "unescape"];
