use super::*;
use crate::parallel::residency::{MemoryPressure, ResidencyBudget};
use crate::parallel::skeleton::diff_skeletons;
use std::fs;
use std::path::Path;
include!("parallel_tests_parts/part_00.rs");
include!("parallel_tests_parts/part_01.rs");
include!("parallel_tests_parts/part_02.rs");
include!("parallel_tests_parts/part_03.rs");
include!("parallel_tests_parts/part_04.rs");
include!("parallel_tests_parts/part_05.rs");
include!("parallel_tests_parts/part_06.rs");
include!("parallel_tests_parts/part_07.rs");
include!("parallel_tests_parts/part_08.rs");
include!("parallel_tests_parts/part_09.rs");
include!("parallel_tests_parts/part_10.rs");
include!("parallel_tests_parts/part_11.rs");
include!("parallel_tests_parts/part_12.rs");
include!("parallel_tests_parts/part_13.rs");
include!("parallel_tests_parts/part_14.rs");
include!("parallel_tests_parts/part_15.rs");
include!("parallel_tests_parts/part_16.rs");
include!("parallel_tests_parts/part_17.rs");
include!("parallel_tests_parts/part_18.rs");
include!("parallel_tests_parts/part_19.rs");
