//! Source map tests - Part 4 (JSX, utility types, remaining tests)

use crate::context::emit::EmitContext;
use crate::emitter::{Printer, PrinterOptions, ScriptTarget};
use crate::lowering::LoweringPass;
use crate::parser::ParserState;
use crate::source_map_test_utils::decode_mappings;
use serde_json::Value;
include!("source_map_tests_4_parts/part_00.rs");
include!("source_map_tests_4_parts/part_01.rs");
include!("source_map_tests_4_parts/part_02.rs");
include!("source_map_tests_4_parts/part_03.rs");
include!("source_map_tests_4_parts/part_04.rs");
include!("source_map_tests_4_parts/part_05.rs");
include!("source_map_tests_4_parts/part_06.rs");
include!("source_map_tests_4_parts/part_07.rs");
include!("source_map_tests_4_parts/part_08.rs");
include!("source_map_tests_4_parts/part_09.rs");
include!("source_map_tests_4_parts/part_10.rs");
include!("source_map_tests_4_parts/part_11.rs");
include!("source_map_tests_4_parts/part_12.rs");
include!("source_map_tests_4_parts/part_13.rs");
include!("source_map_tests_4_parts/part_14.rs");
include!("source_map_tests_4_parts/part_15.rs");
include!("source_map_tests_4_parts/part_16.rs");
include!("source_map_tests_4_parts/part_17.rs");
include!("source_map_tests_4_parts/part_18.rs");
include!("source_map_tests_4_parts/part_19.rs");
include!("source_map_tests_4_parts/part_20.rs");
include!("source_map_tests_4_parts/part_21.rs");
include!("source_map_tests_4_parts/part_22.rs");
