#!/usr/bin/env bash
# =============================================================================
# run-cliff.sh — bench monorepo-NNN fixtures and emit per-file ratios as CSV
# =============================================================================
#
# Per docs/plan/PERF_ARCHITECTURAL_PLAN.md "Step 0", this drives the
# fixtures generated by generate-fixtures.sh, parses the TSZ_PERF_COUNTERS
# dump from each tsz run, and prints a CSV with per-file ratios. The cliff
# is wherever a ratio stops being roughly constant across fixture sizes.
#
# Usage:
#   scripts/bench/scale-cliff/run-cliff.sh                  # default
#   scripts/bench/scale-cliff/run-cliff.sh --skip 003,004   # skip listed
#   scripts/bench/scale-cliff/run-cliff.sh --tsz /path/tsz  # use specific binary
#
# Output: scripts/bench/scale-cliff/results/cliff-<timestamp>.csv
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIXTURES_DIR="$SCRIPT_DIR/fixtures"
RESULTS_DIR="$SCRIPT_DIR/results"

TSZ_BIN="${TSZ_BIN:-/Users/mohsen/.cache/tsz-target/release/tsz}"
SKIP=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip) SKIP="$2"; shift 2 ;;
        --tsz)  TSZ_BIN="$2"; shift 2 ;;
        *) echo "unknown arg: $1"; exit 1 ;;
    esac
done

if [[ ! -x "$TSZ_BIN" ]]; then
    echo "tsz binary not found at $TSZ_BIN. Build with:"
    echo "  CARGO_TARGET_DIR=/Users/mohsen/.cache/tsz-target cargo build --release --bin tsz"
    exit 1
fi

if [[ ! -d "$FIXTURES_DIR" ]]; then
    echo "Fixtures missing. Run scripts/bench/scale-cliff/generate-fixtures.sh first."
    exit 1
fi

mkdir -p "$RESULTS_DIR"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
CSV="$RESULTS_DIR/cliff-${TIMESTAMP}.csv"

# CSV header — column names match the dump labels so a downstream awk/sql is
# straightforward.
{
    printf "fixture,files,total_s,check_s,parse_bind_s,io_read_s,memory_kb"
    printf ",delegate_calls,delegate_misses,delegate_lib_hits,delegate_xfile_hits"
    printf ",checker_state_new,checker_with_parent_cache"
    printf ",overlay_copy_calls,overlay_entries_copied"
    printf ",compute_type_of_symbol_calls"
    printf ",resolver_lookup_calls,resolver_pj_reads"
    printf ",ratio_checkers_per_file,ratio_overlay_per_file,ratio_delegations_per_file,ratio_compute_per_file\n"
} >"$CSV"

# Pull a labeled value from a tsz extendedDiagnostics + counter dump.
extract_seconds() {
    local label="$1"
    local file="$2"
    awk -v label="$label" -F: '$0 ~ "^"label {gsub(/[^0-9.]/, "", $2); print $2; exit}' "$file"
}

extract_kb() {
    local label="$1"
    local file="$2"
    awk -v label="$label" -F: '$0 ~ "^"label {gsub(/[^0-9]/, "", $2); print $2; exit}' "$file"
}

extract_counter() {
    # Counters dump format is two-or-more spaces followed by an integer at end of line.
    local label="$1"
    local file="$2"
    awk -v label="$label" '$0 ~ label {for (i=NF;i>=1;i--) if ($i ~ /^[0-9]+$/) {print $i; exit}}' "$file"
}

run_one() {
    local name="$1"
    local dir="$FIXTURES_DIR/$name"
    if [[ ! -d "$dir" ]]; then
        echo "  skip $name: fixture missing"
        return
    fi
    local tsconfig="$dir/tsconfig.json"
    local file_count
    file_count=$(find "$dir/packages" -name '*.ts' 2>/dev/null | wc -l | tr -d ' ')
    local out
    out=$(mktemp)
    echo "  benching $name ($file_count .ts files)"
    TSZ_PERF_COUNTERS=1 "$TSZ_BIN" \
        --extendedDiagnostics --noEmit \
        -p "$tsconfig" \
        >"$out" 2>&1 || true

    local total_s check_s parse_bind_s io_read_s mem_kb
    total_s=$(extract_seconds "Total time" "$out")
    check_s=$(extract_seconds "Check" "$out")
    parse_bind_s=$(extract_seconds "Parse \\& Bind" "$out")
    io_read_s=$(extract_seconds "I/O Read" "$out")
    mem_kb=$(extract_kb "Memory used" "$out")

    local delegate_calls delegate_misses delegate_lib delegate_xfile
    delegate_calls=$(extract_counter "calls *" "$out" | head -1)
    delegate_lib=$(extract_counter "cache hits .lib" "$out")
    delegate_xfile=$(extract_counter "cache hits .cross-file" "$out")
    delegate_misses=$(extract_counter "misses .full work" "$out")

    local checker_new checker_with_parent
    checker_new=$(extract_counter "CheckerState::new" "$out")
    checker_with_parent=$(extract_counter "::with_parent_cache" "$out")

    local overlay_calls overlay_entries
    # Format is "copy_symbol_file_targets   N  (M entries copied)"
    overlay_calls=$(awk '/copy_symbol_file_targets/ {for (i=1;i<=NF;i++) if ($i ~ /^[0-9]+$/) {print $i; exit}}' "$out")
    # macOS awk doesn't support match() with array arg; use sed instead.
    overlay_entries=$(grep "copy_symbol_file_targets" "$out" | sed -E 's/.*\(([0-9]+) entries.*/\1/' | head -1)
    if ! [[ "$overlay_entries" =~ ^[0-9]+$ ]]; then overlay_entries=0; fi

    local compute_calls
    compute_calls=$(extract_counter "compute_type_of_symbol" "$out" | head -1)
    if [[ -z "$compute_calls" ]]; then
        # Fallback: the dump has the label on its own line, then "total calls    NNN" beneath.
        compute_calls=$(awk '/compute_type_of_symbol:/{found=1; next} found && /total calls/{for (i=1;i<=NF;i++) if ($i ~ /^[0-9]+$/) {print $i; exit}}' "$out")
    fi

    local resolver_lookup resolver_pj
    resolver_lookup=$(awk '/Resolver:/{found=1; next} found && /lookup calls/{for (i=1;i<=NF;i++) if ($i ~ /^[0-9]+$/) {print $i; exit}}' "$out")
    resolver_pj=$(awk '/read_package_json calls/{for (i=1;i<=NF;i++) if ($i ~ /^[0-9]+$/) {print $i; exit}}' "$out")

    # Defaults to keep CSV well-formed when a number wasn't extracted.
    : "${total_s:=0}"; : "${check_s:=0}"; : "${parse_bind_s:=0}"; : "${io_read_s:=0}"; : "${mem_kb:=0}"
    : "${delegate_calls:=0}"; : "${delegate_misses:=0}"; : "${delegate_lib:=0}"; : "${delegate_xfile:=0}"
    : "${checker_new:=0}"; : "${checker_with_parent:=0}"
    : "${overlay_calls:=0}"; : "${overlay_entries:=0}"
    : "${compute_calls:=0}"
    : "${resolver_lookup:=0}"; : "${resolver_pj:=0}"

    # Per-file ratios — these are the headline cliff numbers.
    local ratio_checkers ratio_overlay ratio_delegations ratio_compute
    if (( file_count > 0 )); then
        ratio_checkers=$(awk -v a="$checker_with_parent" -v b="$file_count" 'BEGIN{printf "%.2f", a/b}')
        ratio_overlay=$(awk -v a="$overlay_entries" -v b="$file_count" 'BEGIN{printf "%.0f", a/b}')
        ratio_delegations=$(awk -v a="$delegate_calls" -v b="$file_count" 'BEGIN{printf "%.2f", a/b}')
        ratio_compute=$(awk -v a="$compute_calls" -v b="$file_count" 'BEGIN{printf "%.2f", a/b}')
    else
        ratio_checkers=0; ratio_overlay=0; ratio_delegations=0; ratio_compute=0
    fi

    {
        printf "%s,%s,%s,%s,%s,%s,%s" \
            "$name" "$file_count" "$total_s" "$check_s" "$parse_bind_s" "$io_read_s" "$mem_kb"
        printf ",%s,%s,%s,%s" \
            "$delegate_calls" "$delegate_misses" "$delegate_lib" "$delegate_xfile"
        printf ",%s,%s" \
            "$checker_new" "$checker_with_parent"
        printf ",%s,%s" \
            "$overlay_calls" "$overlay_entries"
        printf ",%s" \
            "$compute_calls"
        printf ",%s,%s" \
            "$resolver_lookup" "$resolver_pj"
        printf ",%s,%s,%s,%s\n" \
            "$ratio_checkers" "$ratio_overlay" "$ratio_delegations" "$ratio_compute"
    } >>"$CSV"

    rm -f "$out"
}

skip_set() {
    local name="${1#monorepo-}"
    [[ ",$SKIP," == *",$name,"* ]]
}

for name in monorepo-001 monorepo-002 monorepo-003 monorepo-004 monorepo-005 monorepo-006; do
    if skip_set "$name"; then
        echo "  skip $name (--skip)"
        continue
    fi
    run_one "$name"
done

echo
echo "CSV: $CSV"
echo
column -s, -t "$CSV"
